### ISSUE TITLE
Unhelpful error message with non-vanilla blocks

### ISSUE THREAD

**Issue by dteviot** [Juggernaut93/Projector2Assembler#4]
If you run the Projector2LCD script without updating it, you get an error message saying "Projector is not projecting".
This is not helpful.
Script can be modified to ignore unknown blocks by changing GetComponents() to

```C++
        public Dictionary<string, int> GetComponents(string definition)
        {
            return blueprints.ContainsKey(blockName)
                ? blueprints[definition]
                : new Dictionary<string, int>();
        }
```

But I wonder if a better solution would be to send a message saying something like:
> Unknown Blocks in Blueprint. Go to https://github.com/Juggernaut93/Projector2Assembler, and follow instructions for BlockDefinitionExtractor.

If you like, I can prepare a Pull Request

**Comment by Juggernaut93** [comment]
I wouldn't silently ignore the error, a better error message is definitely
the way. I'd welcome a pull request for sure, thank you!

Il dom 23 giu 2024, 02:18 dteviot ***@***.***> ha scritto:

**Comment by dteviot** [comment]
To reproduce error.
1. Load https://steamcommunity.com/sharedfiles/filedetails/?id=1907643756 (Athena Mobile Weapons Platform) into a projector.
2. Save game
3. Enable "Nanobot Build and Repair System" for save game and reload
4. Load projector with (Athena Mobile Weapons Platform) again
5. Run Script Projector2LCD

**Comment by Juggernaut93** [comment]
Merged, thank you!
